# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

c.fonts.monospace = 'Ubuntu Mono'
c.fonts.completion.category = '12pt monospace'
c.fonts.completion.entry = '12pt monospace'
c.fonts.debug_console = '12pt monospace'
c.fonts.downloads = '12pt monospace'
c.fonts.hints = '12pt monospace'
c.fonts.keyhint = '12pt monospace'
c.fonts.messages.error = '12pt monospace'
c.fonts.messages.info = '12pt monospace'
c.fonts.messages.warning = '12pt monospace'
c.fonts.prompts = '12pt monospace'
c.fonts.statusbar = '12pt monospace'
c.fonts.tabs = '12pt monospace'

c.fonts.web.size.minimum = 13

c.zoom.default = 110

c.bindings.key_mappings['<Ctrl-g>'] = '<Escape>'

c.spellcheck.languages = ['en-AU']

c.content.host_blocking.enabled = True
c.completion.cmd_history_max_items = 100
# c.completion.web_history_max_items = -1
c.content.autoplay = False

# MPV
config.bind(',m', 'hint links spawn mpv {hint-url}')
# view_in_mpv script needs be rewritten to allow the
# use of link hints
# config.bind(',m', 'hint links spawn -u view_in_mpv')
# config.bind(',p', 'spawn -u password_fill')

config.bind('d', 'scroll-page 0 0.5')
config.bind('u', 'scroll-page 0 -0.5')

config.bind('x', 'tab-close')
config.bind('X', 'undo')

config.bind('H', 'back')
config.bind('L', 'forward')

config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')

config.bind('b', 'set-cmd-text -s :buffer')

config.bind('yo', 'spawn -u org_capture')
config.bind('yO', 'spawn -u yank_org_link')
config.bind(',q', 'set-cmd-text -s :quickmark-load')

# qute-pass userscript for pass
config.bind('<z><l>', 'spawn --userscript qute-pass')
config.bind('<z><u><l>', 'spawn --userscript qute-pass --username-only')
config.bind('<z><p><l>', 'spawn --userscript qute-pass --password-only')
config.bind('<z><o><l>', 'spawn --userscript qute-pass --otp-only')
